module.exports = {
  GET_CATEGORIES: 'GET_CATEGORIES',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  UPDATE_SECTION: 'UPDATE_SECTION',
  SORT_CATEGORY_SECTIONS: 'SORT_CATEGORY_SECTIONS',
  SORT_SECTION_ITEMS: 'SORT_SECTION_ITEMS',
  SORT_CATEGORIES: 'SORT_CATEGORIES'
};
